db:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver


#We can have here other configuration specific for dev environment