name: Build And Deploy Spring Boot App
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Show working directory and files
        run: |
          pwd
          ls -R

      - name: Build and test with maven
        run: mvn clean package
        working-directory: demo

      - name: Archive JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: springboot-jar
          path: target/*.jar


  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v4
        with:
          name: springboot-jar

      - name: Output contents
        run: ls

      - name: Deploy
        run: echo "Deploying...."




